[package]
name = "wake-on-lan"
version = "0.2.0"
authors = ["Teemu Remes <teemu@teemuremes.com>"]
description = "A library for creating and sending Wake-on-LAN magic packets"
license = "MIT OR Apache-2.0"
repository = "https://github.com/teemuremes/wake-on-lan-rust"